

-- 20171214 - top varianst load
-- OLD metadat structure
SELECT distinct ID_PH.TBL ,
                DATASET.TBL,
                PROP_ID_PH.ID,
                PROP_ID_PH.PH
FROM PROP_ID_PH, PROP, ID_PH,DATASET
WHERE PROP_ID_PH.PROP = PROP.PROP
AND ID_PH.ID = PROP_ID_PH.ID
AND ID_PH.PH = PROP_ID_PH.PH
AND MEANING = 'P_VALUE' AND
DATASET.VER = 'mdv29'
AND DATASET.ID = PROP_ID_PH.ID ;


-- NEW metadata structure
SELECT distinct META_DATASET.TBL,META_ID_PH.ID,META_PROP_DATASET_PH.PH ,META_DATASET_PH.TBL
FROM META_PROP_DATASET_PH,
     META_PROP,
     META_MDV,
     META_ID_PH,
     META_DATASET,
     META_DATASET_PH
WHERE META_PROP_DATASET_PH.PROP = META_PROP.PROP
AND META_PROP_DATASET_PH.DATASET = META_DATASET.DATASET
AND META_PROP_DATASET_PH.DATASET = META_MDV.DATASET
AND META_MDV.ID = META_ID_PH.ID
AND META_ID_PH.PH = META_PROP_DATASET_PH.PH
AND MEANING = 'P_VALUE'
AND VER = "mdv91";



select tv.VAR_ID,tv.dataset,tv.P_VALUE,tv.BETA,tv.MDV,
tv.phenotype,tv.AF,kg.EAF,tv.POS,tv.GENE,tv.CHROM,tv.MOST_DEL_SCORE
from TOP_VARIANTS_MDV29  tv
inner join 1kg_phase1_dv1 kg on (tv.VAR_ID=kg.VAR_ID) limit 1;


